/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Interface;



import br.com.Interface.TelaPrincipal;
import br.com.Interface.TelaPrincipal;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Volkova
 */
public class Clientes extends javax.swing.JFrame {
    
        DefaultTableModel dm; //criando o objeto para a tabela
       
    /**
     * Creates new form Clientes
     */
    
    public Clientes() {
        initComponents();
        
        setLocationRelativeTo(null);//para abrir centralizado
        
        CreateColumns();  //criando as colunas da minha tabela
        
        TabelaClientes.setAutoCreateRowSorter(true);//pra colocar em ordem alfabetica no campo que vc quiser na tabela
        
        //iniciando a tabela com o botao atualizar desabilitado
        JbAtualizar.setEnabled(false);
    
    }
     private void CreateColumns(){
        dm= (DefaultTableModel)TabelaClientes.getModel(); //instanciando a tabela
        
        //criando o topo da tabela
        dm.addColumn("Nome");
        dm.addColumn("Bairro");
        dm.addColumn("Telefone");
        dm.addColumn("E-mail");
        dm.addColumn("CPF");
        dm.addColumn("Endereço");
        dm.addColumn("CEP");
        dm.addColumn("Ponto de Referência");
        
        //Escondendo as colunas 
        TabelaClientes.getColumnModel().getColumn(4).setWidth(0);
        TabelaClientes.getColumnModel().getColumn(4).setMinWidth(0);
        TabelaClientes.getColumnModel().getColumn(4).setMaxWidth(0);
        
        TabelaClientes.getColumnModel().getColumn(5).setWidth(0);
        TabelaClientes.getColumnModel().getColumn(5).setMinWidth(0);
        TabelaClientes.getColumnModel().getColumn(5).setMaxWidth(0);
        
        TabelaClientes.getColumnModel().getColumn(6).setWidth(0);
        TabelaClientes.getColumnModel().getColumn(6).setMinWidth(0);
        TabelaClientes.getColumnModel().getColumn(6).setMaxWidth(0);
        
        TabelaClientes.getColumnModel().getColumn(7).setWidth(0);
        TabelaClientes.getColumnModel().getColumn(7).setMinWidth(0);
        TabelaClientes.getColumnModel().getColumn(7).setMaxWidth(0);
        
        
    }
     private void Populate(String nome, String bairro, String tel, String email, String cpf, String endereco, String cep, String pont){
        //adicionando os dados na linha da tabela
        
        String[] rowData={nome,bairro,tel,email,cpf,endereco,cep,pont};
        dm.addRow(rowData);
        
    }
     
     private void filter(String query){
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<>(dm);
        TabelaClientes.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txnome = new javax.swing.JTextField();
        Txcpf = new javax.swing.JFormattedTextField();
        Txend = new javax.swing.JTextField();
        Txbai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txref = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        Txemail = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaClientes = new javax.swing.JTable();
        Jblimpar = new javax.swing.JButton();
        Jbsalvar = new javax.swing.JButton();
        JbAtualizar = new javax.swing.JButton();
        Jbexcluir = new javax.swing.JButton();
        Jbver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pesquisa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Edi = new javax.swing.JButton();
        Txcep = new javax.swing.JFormattedTextField();
        Txtel = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(10, 10, 59, 28);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome ");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(10, 60, 40, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CPF");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(10, 100, 40, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Telefone");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(10, 140, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Endereço");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(10, 220, 60, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CEP");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(10, 300, 40, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Bairro");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(10, 260, 60, 17);
        jDesktopPane1.add(Txnome);
        Txnome.setBounds(80, 50, 230, 30);

        try {
            Txcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Txcpf.setMinimumSize(new java.awt.Dimension(10, 20));
        Txcpf.setPreferredSize(new java.awt.Dimension(51, 25));
        jDesktopPane1.add(Txcpf);
        Txcpf.setBounds(80, 90, 230, 30);
        jDesktopPane1.add(Txend);
        Txend.setBounds(80, 210, 230, 30);
        jDesktopPane1.add(Txbai);
        Txbai.setBounds(80, 250, 230, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ponto de referência:");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(10, 330, 140, 17);

        Txref.setColumns(20);
        Txref.setRows(5);
        jScrollPane1.setViewportView(Txref);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 350, 300, 70);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("E-mail");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(10, 180, 50, 14);
        jDesktopPane1.add(Txemail);
        Txemail.setBounds(80, 170, 230, 30);

        TabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TabelaClientes);

        jDesktopPane1.add(jScrollPane2);
        jScrollPane2.setBounds(340, 92, 456, 320);

        Jblimpar.setText("Limpar Campos");
        Jblimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JblimparActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Jblimpar);
        Jblimpar.setBounds(10, 460, 110, 28);

        Jbsalvar.setText("Salvar");
        Jbsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbsalvarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Jbsalvar);
        Jbsalvar.setBounds(110, 430, 110, 28);

        JbAtualizar.setText("Atualizar");
        JbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAtualizarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(JbAtualizar);
        JbAtualizar.setBounds(210, 460, 100, 28);

        Jbexcluir.setText("Excluir");
        Jbexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbexcluirActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Jbexcluir);
        Jbexcluir.setBounds(540, 430, 70, 28);

        Jbver.setText("Detalhes");
        Jbver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbverActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Jbver);
        Jbver.setBounds(680, 430, 80, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Clientes");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(340, 10, 90, 29);

        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaKeyReleased(evt);
            }
        });
        jDesktopPane1.add(pesquisa);
        pesquisa.setBounds(430, 50, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Pesquisar");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(350, 60, 60, 17);

        Edi.setText("Editar");
        Edi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdiActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Edi);
        Edi.setBounds(390, 430, 60, 28);

        try {
            Txcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDesktopPane1.add(Txcep);
        Txcep.setBounds(80, 290, 230, 30);

        try {
            Txtel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDesktopPane1.add(Txtel);
        Txtel.setBounds(80, 130, 230, 30);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 800, 500);

        setBounds(0, 0, 816, 539);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //botão voltar
        TelaPrincipal voltar= new TelaPrincipal(); //instanciando um objeto
        voltar.setVisible(true);                   //chamando a classe
        this.dispose();                            //fechando a classe atual
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JbsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbsalvarActionPerformed
        //Botão salvar
        
        if(Txnome.getText().isEmpty()){     //Verificando se o campo está preenchido
            JOptionPane.showMessageDialog(rootPane, "Campo em branco", "Alerta",JOptionPane.INFORMATION_MESSAGE);
            
        }else if(Txcpf.getText().isEmpty()){     //Verificando se o campo está preenchido
            JOptionPane.showMessageDialog(rootPane, "Campo em branco", "Alerta",JOptionPane.INFORMATION_MESSAGE);

        }else if(Txbai.getText().isEmpty()){     //Verificando se o campo está preenchido
            JOptionPane.showMessageDialog(rootPane, "Campo em branco", "Alerta",JOptionPane.INFORMATION_MESSAGE);

        }else if(Txtel.getText().isEmpty()){     //Verificando se o campo está preenchido
            JOptionPane.showMessageDialog(rootPane, "Campo em branco", "Alerta",JOptionPane.INFORMATION_MESSAGE);

        }else if(Txemail.getText().isEmpty()){       //Verificando se o campo está preenchido
            JOptionPane.showMessageDialog(rootPane, "Campo em branco", "Alerta",JOptionPane.INFORMATION_MESSAGE);
            
        }else if(Txend.getText().isEmpty()){       //Verificando se o campo está preenchido
            JOptionPane.showMessageDialog(rootPane, "Campo em branco", "Alerta",JOptionPane.INFORMATION_MESSAGE);
            
        }else if(Txcep.getText().isEmpty()){       //Verificando se o campo está preenchido
            JOptionPane.showMessageDialog(rootPane, "Campo em branco", "Alerta",JOptionPane.INFORMATION_MESSAGE);
                    
        }else{ //Se estiver preenchido
            
            //pegado os dados e enviando para a tabela
            
            Populate(Txnome.getText(), Txbai.getText(), Txtel.getText(), Txemail.getText(), Txcpf.getText(),Txend.getText(), Txcep.getText(), Txref.getText());
            
        
            Txnome.setText("");          //resetando o campo para uma nova inserção 
            Txcpf.setText("");           //resetando o campo para uma nova inserção
            Txbai.setText("");           //resetando o campo para uma nova inserção
            Txtel.setText("");           //resetando o campo para uma nova inserção
            Txemail.setText("");         //resetando o campo para uma nova inserção
            Txend.setText("");           //resetando o campo para uma nova inserção
            Txcep.setText("");           //resetando o campo para uma nova inserção
            Txref.setText("");           //resetando o campo para uma nova inserção
            
        }
  
    }//GEN-LAST:event_JbsalvarActionPerformed

    private void JblimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JblimparActionPerformed
            //Limpar campos
            Txnome.setText("");         //resetando o campo para uma nova inserção 
            Txcpf.setText("");          //resetando o campo para uma nova inserção
            Txbai.setText("");          //resetando o campo para uma nova inserção
            Txtel.setText("");          //resetando o campo para uma nova inserção
            Txemail.setText("");        //resetando o campo para uma nova inserção
            Txend.setText("");          //resetando o campo para uma nova inserção
            Txcep.setText("");          //resetando o campo para uma nova inserção
            Txref.setText("");          //resetando o campo para uma nova inserção
            
            //reativando botoes
            Jbsalvar.setEnabled(true);      //botao salvar
            JbAtualizar.setEnabled(false);  //botão atualizar
            Jbexcluir.setEnabled(true);     //botão excluir
            Jbver.setEnabled(true);         //botão exibir
            
    }//GEN-LAST:event_JblimparActionPerformed

    private void JbexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbexcluirActionPerformed
        DefaultTableModel arm= (DefaultTableModel)TabelaClientes.getModel();  //instanciando a tabela
        arm.removeRow(TabelaClientes.getSelectedRow());    //removendo a parte selecionada
    }//GEN-LAST:event_JbexcluirActionPerformed

    private void JbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAtualizarActionPerformed
        //botao atualizar
        
        //pegando o dado selecionado na tabela e sustituindo.
        dm.setValueAt(Txnome.getText(),TabelaClientes.getSelectedRow(),0 );
        dm.setValueAt(Txbai.getText(),TabelaClientes.getSelectedRow(),1 );
        dm.setValueAt(Txtel.getText(),TabelaClientes.getSelectedRow(),2 );
        dm.setValueAt(Txemail.getText(),TabelaClientes.getSelectedRow(),3 );
        dm.setValueAt(Txcpf.getText(),TabelaClientes.getSelectedRow(),4 );
        dm.setValueAt(Txend.getText(),TabelaClientes.getSelectedRow(),5 );
        dm.setValueAt(Txcep.getText(),TabelaClientes.getSelectedRow(),6 );
        dm.setValueAt(Txref.getText(),TabelaClientes.getSelectedRow(),7 );
        
        //resetando campos depois de substituido os valores
  
            Txnome.setText("");         //resetando o campo para uma nova inserção 
            Txcpf.setText("");          //resetando o campo para uma nova inserção
            Txbai.setText("");          //resetando o campo para uma nova inserção
            Txtel.setText("");          //resetando o campo para uma nova inserção
            Txemail.setText("");        //resetando o campo para uma nova inserção
            Txend.setText("");          //resetando o campo para uma nova inserção
            Txcep.setText("");          //resetando o campo para uma nova inserção
            Txref.setText("");          //resetando o campo para uma nova inserção
            
        //abilitando e desabilitando botoes
        Jbsalvar.setEnabled(true);     //ativando botao salvar
        JbAtualizar.setEnabled(false); //desativando botao atualizar
        Jbexcluir.setEnabled(true);    //ativando botao excluir
        Jbver.setEnabled(true);        //ativando botao exibir
    }//GEN-LAST:event_JbAtualizarActionPerformed

    private void pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyReleased
        //botao pesquisa
        String query= pesquisa.getText().trim(); //pegando o que foi escrito 
        filter(query);
    }//GEN-LAST:event_pesquisaKeyReleased

    private void JbverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbverActionPerformed
        //botão exibir
        
        DescCliente aparecer = new DescCliente(); //instanciando a outra classe
        
        int index = TabelaClientes.getSelectedRow(); //selecionando as colunas do jtable dessa classe
        //TableModel model = new TabelProdutos.getModel();
        TableModel model= (DefaultTableModel)TabelaClientes.getModel(); //instanciandoum ojeto para minha tabela
        String Nome = model.getValueAt(index, 0).toString();          //selecinando o valor da linha da tabela
        String Bairro = model.getValueAt(index, 1).toString();        //selecinando o valor da linha da tabela
        String Telefone = model.getValueAt(index, 2).toString();       //selecinando o valor da linha da tabela
        String Email = model.getValueAt(index, 3).toString();     //selecinando o valor da linha da tabela
        String CPF = model.getValueAt(index, 4).toString();       //selecinando o valor da linha da tabela
        String Endereco = model.getValueAt(index, 5).toString();   //selecinando o valor da linha da tabela
        String CEP = model.getValueAt(index, 6).toString();   //selecinando o valor da linha da tabela
        String Pont = model.getValueAt(index, 7).toString();   //selecinando o valor da linha da tabela
        
        aparecer.setVisible(true);  //fazendo a janela da descrição de produtos visivel
        aparecer.pack();        //ajeitando o tamanho da janela
        aparecer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);     //mostrando como ela pode ser fechada
        
        //Fazendo a outa classe receber os dados dessa classe
        aparecer.Tnome.setText(Nome);
        aparecer.Tbai.setText(Bairro);
        aparecer.Ttel.setText(Telefone);
        aparecer.Temail.setText(Email);
        aparecer.Tcpf.setText(CPF);
        aparecer.Tend.setText(Endereco);
        aparecer.Tcep.setText(CEP);
        aparecer.Tref.setText(Pont);
        
    }//GEN-LAST:event_JbverActionPerformed

    private void EdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdiActionPerformed
         //botao editar
        
        //pegando um valor de um campo específico da tabela e colocando dentro de um textfield específico
        Txnome.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 0).toString());
        Txbai.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 1).toString());
        Txtel.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 2).toString());
        Txemail.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 3).toString());
        Txcpf.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 4).toString());
        Txend.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 5).toString());
        Txcep.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 6).toString());
        Txref.setText(TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 7).toString());
        
        //abilitando e desabilitando botoes
        JbAtualizar.setEnabled(true);
        Jbsalvar.setEnabled(false);
        Jbver.setEnabled(false);
        Jbexcluir.setEnabled(false);
    }//GEN-LAST:event_EdiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edi;
    private javax.swing.JButton JbAtualizar;
    private javax.swing.JButton Jbexcluir;
    private javax.swing.JButton Jblimpar;
    private javax.swing.JButton Jbsalvar;
    private javax.swing.JButton Jbver;
    private javax.swing.JTable TabelaClientes;
    private javax.swing.JTextField Txbai;
    private javax.swing.JFormattedTextField Txcep;
    private javax.swing.JFormattedTextField Txcpf;
    private javax.swing.JTextField Txemail;
    private javax.swing.JTextField Txend;
    private javax.swing.JTextField Txnome;
    private javax.swing.JTextArea Txref;
    private javax.swing.JFormattedTextField Txtel;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField pesquisa;
    // End of variables declaration//GEN-END:variables

}
