/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.Interface;

/**
 *
 * @author Volkova
 */
public class DescCliente extends javax.swing.JFrame {

    /**
     * Creates new form DescCliente
     */
    public DescCliente() {
        initComponents();
        
        setLocationRelativeTo(null);//para abrir centralizado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Ttel = new javax.swing.JFormattedTextField();
        Tcep = new javax.swing.JFormattedTextField();
        Tcpf = new javax.swing.JFormattedTextField();
        Tnome = new javax.swing.JTextField();
        Temail = new javax.swing.JTextField();
        Tend = new javax.swing.JTextField();
        Tbai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tref = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 380));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nome");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(20, 80, 40, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CPF");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(370, 80, 24, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bairro");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(20, 230, 35, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Ponto de referência:");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(330, 170, 130, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Endereço");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(20, 180, 70, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Email");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(20, 130, 31, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CEP");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(20, 280, 25, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Telefone");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(370, 130, 60, 17);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(270, 310, 73, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Informações do Cliente");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(190, 10, 250, 30);

        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("Valores não editáveisl");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(260, 40, 140, 16);

        try {
            Ttel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Ttel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtelActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Ttel);
        Ttel.setBounds(440, 120, 110, 30);

        try {
            Tcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDesktopPane1.add(Tcep);
        Tcep.setBounds(90, 270, 110, 30);

        try {
            Tcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDesktopPane1.add(Tcpf);
        Tcpf.setBounds(440, 70, 110, 30);
        jDesktopPane1.add(Tnome);
        Tnome.setBounds(90, 70, 270, 30);
        jDesktopPane1.add(Temail);
        Temail.setBounds(90, 120, 250, 30);
        jDesktopPane1.add(Tend);
        Tend.setBounds(90, 170, 210, 30);
        jDesktopPane1.add(Tbai);
        Tbai.setBounds(90, 220, 190, 30);

        Tref.setColumns(20);
        Tref.setRows(5);
        jScrollPane1.setViewportView(Tref);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 190, 250, 110);

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 0, 650, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TtelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //botão ok
        this.dispose(); //fecha a tela
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Tbai;
    public javax.swing.JFormattedTextField Tcep;
    public javax.swing.JFormattedTextField Tcpf;
    public javax.swing.JTextField Temail;
    public javax.swing.JTextField Tend;
    public javax.swing.JTextField Tnome;
    public javax.swing.JTextArea Tref;
    public javax.swing.JFormattedTextField Ttel;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
